version: 2
updates:
  - package-ecosystem: "bundler"
    open-pull-requests-limit: 10
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Madrid"
    labels:
      - "dependencies"
      - "backend"
    assignees:
      - "javierav"
    ignore:
      - dependency-name: "rails"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Madrid"
    labels:
      - "dependencies"
    assignees:
      - "javierav"
