require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - "**/bin/**/*"
    - "**/scripts/**/*"
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  SuggestExtensions: true
  TargetRubyVersion: 3.2.2

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/LineLength:
  Max: 130
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - "**/db/migrate/**/*.rb"
Metrics/BlockLength:
  Exclude:
    - "**/config/environments/*.rb"
Metrics/MethodLength:
  Exclude:
    - "**/db/migrate/**/*.rb"

Minitest/MultipleAssertions:
  Enabled: false

Performance/StringIdentifierArgument:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false
Rails/HttpStatus:
  EnforcedStyle: numeric
Rails/SkipsModelValidations:
  Exclude:
    - "**/db/seeds.rb"

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/HashTransformValues:
  Exclude:
    - "**/app/lib/regulated_costs.rb"
Style/OpenStructUse:
  Exclude:
    - "**/test/**/*"
Style/StringLiterals:
  EnforcedStyle: double_quotes
